name: dart_stucture
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
# --------------------------
environment:
  sdk: ^3.7.2
# ----------------------------------

dependencies:
  flutter:
    sdk: flutter

  
  # CupertinoIcons for iOS
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  get: ^4.7.2
  get_storage: ^2.1.1
  get_it: ^8.0.3
  permission_handler: ^12.0.1
  # ---------------------------------
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  # -----------------------------
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  downloads_path_provider_28: ^0.1.2
  flutter_downloader: ^1.12.0
  share_plus: ^11.1.0
  # ---------------------------------------
  rxdart: ^0.28.0
  # Reactive Extensions for advanced operators(like map, filter, merge, ...).
  # -----------------------------
  auto_animated: ^3.2.0
  lottie: ^3.3.1
  dotlottie_loader: ^0.0.5
  # shimmer: ^3.0.0
  # dotted_border: ^2.1.0
  # table_calendar: ^3.2.0
  # dropdown_button2: ^2.3.9
  # mobkit_dashed_border: ^0.0.8
  # fl_chart: ^1.0.0
  # flutter_tts: ^4.2.3
  # flutter_switch: ^0.3.2
  # pdf: ^3.11.3
  # syncfusion_flutter_pdfviewer: ^30.2.7









# ------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:


# ___________________________________________
flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:

  colors:
    inputs:
      - assets/colors/colors.xml

    outputs:
      class_name: AppColors

# _____________________________________________________
flutter:
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/lotties/
   - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf